### ISSUE TITLE
Create Gidhra plugin

### ISSUE THREAD

**Issue by montyly** [crytic/evm_cfg_builder#23]
## Task Description
We should have a [Ghidra](https://github.com/NationalSecurityAgency/ghidra) plugin for evm-cfg-builder.

## Acceptance criteria
- [ ] An evm file can be loaded in Ghidra
- [ ] The CFG is shown
- [ ] The function's name is shown (if recovered by evm-cfg-builder)

## Required Skills
- [ ] Reverse engineering experience
- [ ] Ghidra or IDA experience
- [ ] Experience with Python 3.6
- [ ] Experience with Solidity smart contracts

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 SAI (200.0 USD @ $1.0/SAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $114,607.00 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 1 month from now.
Please review their action plans below:


**1) [igetgames](https://gitcoin.co/igetgames) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?mutate_worker_action=approve&worker=igetgames) | [reject worker](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?mutate_worker_action=reject&worker=igetgames))_.**

I've used IDA Pro for years and have recently been exploring Ghidra and it's rapidly growing ecosystem. This is a cool bounty and I'd love to give it a shot!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727).

**Comment by alagla** [comment]
Ghidra plugins are only built with java. there's no python plugin support.

**Comment by montyly** [comment]
Hi @igetgames and @alagla, thank you for your interest in this bounty. Could you describe a bit more about your plan to solve this issue?

@alagla , my understanding is that Ghidra supports Jython, or alternatively [`ghidra-bridge`](https://pypi.org/project/ghidra-bridge/) can be used.  If both solutions are not good, I am ok if the solution does something like: 
- evm-cfg-builder exports the CFG in a json (or another format)
- the ghidra plugin loads the info, and displays it

**Comment by alagla** [comment]
@montyly  correct me if i'm wrong, it seems to me Ghidra won't be able to load and analyze an evm bytecode without building an internal representation of that first. neither Jython or ghidra_bridge has the functionality to do that. 

I can attempt a Java plugin that consumes .dot files from evm-cfg-builder and process the data in natively.

**Comment by alagla** [comment]
I'll start working when I get accepted on gitcoin. 
Thanks

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 250.00000  SAI (250.0 USD @ $1.0/SAI) has been granted to @alagla for this issue from @ceresstation. ⚡️ 

Nice work @alagla! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page. 

 * $96771.66 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
@alagla Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=100)

**Comment by gitcoinbot** [comment]
@alagla Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/evm_cfg_builder/23/3727?snooze=100)

**Comment by alagla** [comment]
Yes, I'm working on it.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 200.0 SAI  (200.0 USD @ $1.0/SAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $75,976.24 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by adelapie** [comment]
Hello, I wonder what is the status of this issue. I've built a Ghidra module for disassembling EVM bytecode and creating the CFG via evm_cfg_builder in https://github.com/adelapie/ghidra-evm. It would be great to receive feedback.
